/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
    antlr
    id("org.springframework.boot").version("2.1.5.RELEASE")
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-data-jpa:2.1.5.RELEASE")
    implementation("org.springframework.boot:spring-boot-starter-web:2.1.5.RELEASE")
    implementation("org.springframework.boot:spring-boot-starter-websocket:2.1.5.RELEASE")
    implementation("org.springframework.boot:spring-boot-starter-security:2.1.5.RELEASE")
    implementation("org.springframework.security:spring-security-messaging:5.1.5.RELEASE")
    implementation("io.jsonwebtoken:jjwt:0.9.0")
    implementation("org.springframework.security:spring-security-oauth2-client:5.1.5.RELEASE")
    implementation("org.springframework.security:spring-security-oauth2-jose:5.1.5.RELEASE")
    implementation("org.springframework.boot:spring-boot-configuration-processor:2.1.5.RELEASE")
    implementation("org.liquibase:liquibase-core:3.6.3")
    implementation("org.antlr:antlr4-runtime:4.7.2")
    implementation("org.yaml:snakeyaml:1.23")
    implementation("com.amazonaws:aws-java-sdk-s3:1.11.860")
    implementation("com.amazonaws:aws-java-sdk-textract:1.11.860")
    runtimeOnly("org.springframework.boot:spring-boot-devtools:2.1.5.RELEASE")
    runtimeOnly("com.h2database:h2:1.4.199")
    runtimeOnly("org.postgresql:postgresql:42.2.5")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.1.5.RELEASE")
    testImplementation("org.springframework.security:spring-security-test:5.1.5.RELEASE")
    compileOnly("org.projectlombok:lombok:1.18.18")

    compileOnly("org.projectlombok:lombok:1.18.20")
    annotationProcessor("org.projectlombok:lombok:1.18.20")
    testCompileOnly("org.projectlombok:lombok:1.18.20")
    testAnnotationProcessor("org.projectlombok:lombok:1.18.20")

    annotationProcessor("org.hibernate:hibernate-jpamodelgen:5.3.10.Final")

    annotationProcessor("javax.xml.bind:jaxb-api:2.3.1")

    antlr("org.antlr:antlr4:4.7.2")
}

group = "com.brennaswitzer"
version = "0.0.1-SNAPSHOT"
description = "cookbook"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<AntlrTask>() {
    arguments = arguments + listOf("-visitor", "-no-listener", "-long-messages")
}
